name: Daily pulse
on:
  schedule:
    - cron: "0 12 * * *"   # 12:00 UTC ~= 14:00 Europe/Ljubljana (сейчас)
  workflow_dispatch:
permissions:
  contents: write
jobs:
  pulse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: true }
      - name: Touch .pulse
        run: |
          date +"%Y-%m-%d %H:%M:%S" >> .pulse
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .pulse
          git commit -m "chore(pulse): $(date -u +'%F %T') (GH Actions)" || echo "No changes"
          git push
